customhost = "ntnemployee1.clsc8yck0mz7.us-east-1.rds.amazonaws.com"
customuser = "aws_user1"
custompass = "12345678"
customdb = "ntnemployee1"
custombucket = "nicolechin-bucket"
customregion = "us-east-1"
